{
    'name': 'Core UI',
    'version': '19.0.1.0.0',
    'license': 'LGPL-3',
    'category': 'AbdinSupplyChain',
    'author': 'Abdin Pharmacies',
    'developer': 'Alhassan Hossny',
    'summary': 'Centralized Design System and Component Workspace',
    'description': '''
        Core UI Design System
        =====================
        Complete centralized UI foundation for every module.
        Eliminates duplicated UI, enforces consistency, and provides
        a professional component workspace directly inside Odoo.
    ''',
    'application': True,
    'depends': ['base', 'base_setup', 'web'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'views/res_config_settings.xml',
        'views/component_views.xml',
        'views/category_views.xml',
        'views/token_views.xml',
        'views/pattern_views.xml',
        'views/client_actions.xml',
        'views/component_templates.xml',
        'data/categories_data.xml',
        'data/design_tokens_data.xml',
        'data/components_data.xml',
        'data/patterns_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ab_core_ui/static/src/scss/core_ui_variables.scss',
            'ab_core_ui/static/src/scss/core_ui_tokens.scss',
            'ab_core_ui/static/src/scss/core_ui_components.scss',
            'ab_core_ui/static/src/scss/core_ui_transition.scss',
            'ab_core_ui/static/src/scss/core_ui_workspace.scss',
            'ab_core_ui/static/src/scss/core_ui_design_lab.scss',
            'ab_core_ui/static/src/js/core_ui_transition.js',
            'ab_core_ui/static/src/core_ui/registry.js',
            'ab_core_ui/static/src/core_ui/renderer.js',
            'ab_core_ui/static/src/core_ui/components/progress_bar/progress_bar.js',
            'ab_core_ui/static/src/core_ui/components/progress_bar/index.js',
            'ab_core_ui/static/src/core_ui/components/button/button.js',
            'ab_core_ui/static/src/core_ui/components/button/index.js',
            'ab_core_ui/static/src/core_ui/components/badge/badge.js',
            'ab_core_ui/static/src/core_ui/components/badge/index.js',
            'ab_core_ui/static/src/core_ui/components/alert/alert.js',
            'ab_core_ui/static/src/core_ui/components/alert/index.js',
            'ab_core_ui/static/src/core_ui/components/timeline/timeline.js',
            'ab_core_ui/static/src/core_ui/components/timeline/index.js',
            'ab_core_ui/static/src/core_ui/components/stat_card/stat_card.js',
            'ab_core_ui/static/src/core_ui/components/stat_card/index.js',
            'ab_core_ui/static/src/core_ui/components/index.js',
            'ab_core_ui/static/src/core_ui/design_lab/design_lab_config.js',
            'ab_core_ui/static/src/core_ui/design_lab/design_lab.js',
            'ab_core_ui/static/src/core_ui/design_lab/profile_preview_card.js',
            'ab_core_ui/static/src/core_ui/preview_card.js',
            'ab_core_ui/static/src/js/core_ui_search.js',
            'ab_core_ui/static/src/js/core_ui_sidebar.js',
            'ab_core_ui/static/src/js/core_ui_gallery.js',
            'ab_core_ui/static/src/js/core_ui_inspector.js',
            'ab_core_ui/static/src/core_ui/preferences.js',
            'ab_core_ui/static/src/js/core_ui_settings_card.js',
            'ab_core_ui/static/src/js/core_ui_notebook.js',
            'ab_core_ui/static/src/js/core_ui_workspace.js',
            'ab_core_ui/static/src/xml/core_ui_workspace.xml',
            'ab_core_ui/static/src/xml/core_ui_components.xml',
            'ab_core_ui/static/src/core_ui/design_lab/design_lab.xml',
            'ab_core_ui/static/src/core_ui/design_lab/profile_preview_card.xml',
            'ab_core_ui/static/src/core_ui/preview_card.xml',
            'ab_core_ui/static/src/core_ui/components/progress_bar/progress_bar.xml',
            'ab_core_ui/static/src/core_ui/components/button/button.xml',
            'ab_core_ui/static/src/core_ui/components/badge/badge.xml',
            'ab_core_ui/static/src/core_ui/components/alert/alert.xml',
            'ab_core_ui/static/src/core_ui/components/timeline/timeline.xml',
            'ab_core_ui/static/src/core_ui/components/stat_card/stat_card.xml',
        ],
    },
    'installable': True,
}
