{
    'name': 'Deployment Manager',
    'version': '19.0.4.14.3',
    'license': 'LGPL-3',
    'category': 'Administration',
    'author': 'Abdin Pharmacies',
    'developer': 'emadco88',
    'application': True,
    'depends': ['base', 'mail', 'queue_job'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/request_rules.xml',
        'security/revision_security.xml',
        'security/health_security.xml',
        'views/menus.xml',
        'data/sequences.xml',
        'data/queue_jobs.xml',
        'data/config_parameters.xml',
        'views/deployment_views.xml',
        'views/execution_views.xml',
        'views/request_targets_views.xml',
        'views/odoo_logs_views.xml',
        'views/batch_views.xml',
        'views/display_order_views.xml',
        'views/command_editor_views.xml',
        'views/command_type_views.xml',
        'views/command_parameters_views.xml',
        'wizard/server_import_views.xml',
        'wizard/resolution_views.xml',
        'wizard/manual_resolution_views.xml',
        'wizard/recovery_views.xml',
        'wizard/conflict_views.xml',
        'views/request_security_views.xml',
        'views/conflict_resolution_views.xml',
        'views/dependency_views.xml',
        'views/script_revision_views.xml',
        'wizard/script_update_views.xml',
        'views/health_report_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ab_deploy/static/src/scss/command_editor.scss',
            'ab_deploy/static/src/js/ssh_failure_notification.js',
            'ab_deploy/static/src/xml/ssh_failure_notification.xml',
        ],
    },
    'installable': True,
}
