from odoo import api, models


CITY_AR_TO_EN = {
    'ابشواي': 'Abshway',
    'ابنوب': 'Abnub',
    'ابو المطامير': 'Abu Almatamir',
    'ابو تشت': 'Abu Tisht',
    'ابو تيج': 'Abu Tij',
    'ابو حماد': 'Abu Hamaad',
    'ابو حمص': 'Abu Hims',
    'ابو قرقاص': 'Abu Qarqas',
    'ابو كبير': 'Abu Kabir',
    'اجا': 'Aja',
    'اخميم': 'Akhimim',
    'ادفو': 'Adfu',
    'ادكو': 'Adku',
    'ارمنت': 'Armant',
    'اسنا': 'Asina',
    'اسوان': 'Aswan',
    'اسيوط': 'Assiut',
    'اشمون': 'Ashmun',
    'اطسا': 'Atisan',
    'اطفيح': 'Atfih',
    'الابراهيمية': 'Alabrahimia',
    'الاربعين': 'Alarbaeayn',
    'الاسماعيلية': 'Ismailia',
    'الاقصر': 'Luxor',
    'الباجور': 'Albajur',
    'البداري': 'Albidariu',
    'البدرشين': 'Albadrashin',
    'البساتين ودار السلام': 'Albasatin Wadar Alsalam',
    'البعيرات': 'Albaeayrat',
    'البلينا': 'Alblina',
    'التبين': 'Altabayun',
    'التبين -حلوان': 'Altabayun -halwan',
    'التل الكبير': 'Altal-alkabir',
    'الجمالية': 'Aljamalia',
    'الجمرك': 'Aljumruk',
    'الحامول': 'Alhamul',
    'الحسنة': 'Alhasana',
    'الحسينية': 'Alhusaynia',
    'الحمام': 'Alhamam',
    'الحي الاول': 'Alhayu Alawl',
    'الحي التاسع': 'Alhayu Altaasie',
    'الحي الثالث': 'Alhayu Althaalith',
    'الحي الثامن': 'Alhayu Althaamin',
    'الحي الثاني': 'Alhayu Althaani',
    'الحي الثاني عشر': 'Alhayu Althaani Eashar',
    'الحي الحادي عشر': 'Alhayu Alhadi Eashar',
    'الحي الخامس': 'Alhayu Alkhamis',
    'الحي الرابع': 'Alhayu Alraabie',
    'الحي السابع': 'Alhayu Alsaabie',
    'الحي السادس': 'Alhayu Alsaadis',
    'الحي العاشر': 'Alhayu Aleashir',
    'الخارجة': 'Alkharija',
    'الخانكة': 'Alkhanika',
    'الخليفة و المقطم': 'Alkhalifat W Almuqatam',
    'الداخلة': 'Aldaakhila',
    'الدقي': 'Alduqi',
    'الدلنجات': 'Aldilnajat',
    'الرحمانية': 'Alrahmania',
    'الرياض': 'Alriyad',
    'الزاوية الحمراء': "Alzaawiat Alhamra'",
    'الزرقا': 'Alzarqa',
    'الزقازيق': 'Alzaqaziq',
    'الزيتون': 'Alzaytun',
    'الساحل': 'Alsaahil',
    'السادس من اكتوبر': '6th of October',
    'السلام': 'Alsalam',
    'السنبلاوين': 'Alsanbilawayn',
    'السنطة': 'Alsunta',
    'السويس': 'Suez',
    'السيدة زينب': 'Alsayidat Zaynab',
    'الشرابية': 'Alsharabia',
    'الشرق': 'Alsharq',
    'الشهداء': "Alshuhada'",
    'الصالحية': 'Alsaalihia',
    'الصف': 'Alsaf',
    'الطود': 'Altuwd',
    'العاشر من رمضان': 'Aleashir Min Ramadan',
    'العامرية': 'Aleamiria',
    'العجمي': 'Aleajamiu',
    'العدوة': 'Aleudwa',
    'العريش': 'Alearish',
    'العسيرات': 'Aleasayrat',
    'العياط': 'Aleayaat',
    'الغردقة': 'Alghardaqa',
    'الغنايم': 'Alghanayim',
    'الفتح': 'Alfath',
    'الفرافرة': 'Alfarafira',
    'الفشن': 'Alfashan',
    'الفيوم': 'Alfayuwm',
    'القاهرة': 'Cairo',
    'القرين': 'Alqarin',
    'القصاصين': 'Alqasaasayn',
    'القصير': 'Alqasayr',
    'القناطر الخيرية': 'Alqanatir Alkhayria',
    'القنايات': 'Alqanayat',
    'القنطرة شرق': 'Alqantarat Sharq',
    'القنطرة غرب': 'Alqantarat Gharb',
    'الكردي': 'Alkurdiu',
    'المحلة الكبري - حي اول': 'Almahalat Alkibriu - Hay Awl',
    'المحلة الكبري - حي ثاني': 'Almahalat Alkibriu - Hayun Thani',
    'المحمودية': 'Almahmudi',
    'المراغة': 'Almuragha',
    'المرج': 'Almarj',
    'المطرية': 'Almatria',
    'المطرية-الدقهلية': 'Almatriati-aldaqahlia',
    'المعادي': 'Almaeadi',
    'المعصرة': 'Almaesara',
    'المنتزة': 'Almuntaza',
    'المنزلة': 'Almanzila',
    'المنشاة': 'Almunsha',
    'المنصورة': 'Almansura',
    'المنيا': 'Minya',
    'المنيا الجديدة': 'Alminya Aljadida',
    'المهندسين': 'Almuhandisin',
    'الموسكي': 'Almuski',
    'النزهة': 'Alnuzha',
    'النهضة والهايكستب': 'Alnahdat Walhaykistub',
    'النوبارية الجديدة': 'Alnuwbariat Aljadida',
    'الواحات البحرية': 'Alwahat Albahria',
    'الواسطي': 'Alwasty',
    'الوايلي': 'Alwayli',
    'الوسط': 'Alwasat',
    'الوقف': 'Alwaqf',
    'امبابة': 'Ambabatan',
    'اهناسيا': 'Ahnasiana',
    'اولاد صقر': 'Awlad Saqr',
    'ايتاي البارود': 'Aytay Albarwd',
    'بئر العبد': 'Bir Aleabd',
    'باب الشعرية': 'Bab Alshieria',
    'ببا': 'Baba',
    'برج العرب': 'Burj Alearab',
    'بركة السبع': 'Barakat Alsabe',
    'بسيون': 'Bisyuwn',
    'بلبيس': 'Balbis',
    'بلطيم': 'Biltim',
    'بلقاس': 'Bilqas',
    'بنها العسل': 'Banaha Aleasal',
    'بني سويف': 'Buni Suayf',
    'بني عبيد': 'Buni Eubayd',
    'بني مزار': 'Buni Mazar',
    'بورسعيد': 'Port Said',
    'بيلا': 'Bila',
    'تلا': 'Tala',
    'تمي الامديد': 'Tamiy Alamadid',
    'جرجا': 'Jarja',
    'جمصة': 'Jumsa',
    'جهينة': 'Jahina',
    'حدائق القبة': 'Hadayiq Alquba',
    'حلوان': 'Hulwan',
    'حوش عيسي': 'Hwsh Eisi',
    'حي الجنوب': 'Hayu Aljanub',
    'حي الزهور': 'Hayu Alzuhur',
    'حي الشرق': 'Hayu Alsharq',
    'حي الضواحي': 'Hayu Aldawahi',
    'حي المستقبل.( مدينة 15 مايو سابقا)': 'Hayu Almustaqbali.( Madinat 15 Mayu Sabqa)',
    'حي المناخ': 'Hayu Almunakh',
    'حي الهرم': 'Hayu Alharam',
    'حي بورفؤاد': 'Hay Port Fouad',
    'حي فيصل': 'Hay Faisal',
    'دار السلام': 'Dar Alsalam',
    'دراو': 'Diraw',
    'دسوق': 'Dusuq',
    'دشنا': 'Dishana',
    'دكرنس': 'Dikrans',
    'دمنهور': 'Dimanhur',
    'دمياط': 'Damietta',
    'دير مواس': 'Dyr Mwas',
    'ديرب نجم': 'Dirb Najm',
    'ديروط': 'Dirut',
    'راس سدر': 'Ras Sudar',
    'راس غارب': 'Ras Gharib',
    'رشيد': 'Rashid',
    'روض الفرج': 'Rawd Alfaraj',
    'زفتي': 'Zafti',
    'ساحل سليم': 'Sahil Salim',
    'ساقلته': 'Saqalatuh',
    'سرس الليان': 'Sars Alliyan',
    'سفاجا': 'Safaja',
    'سمالوط': 'Samalut',
    'سمسطا': 'Samsta',
    'سمنود': 'Samnud',
    'سنورس': 'Sanuris',
    'سوهاج': 'Suhaj',
    'سيدي سالم': 'Sayidi Salim',
    'شبرا': 'Shubra',
    'شبرا الخيمة': 'Shubra Alkhayma',
    'شبراخيت': 'Shubrakhit',
    'شبين القناطر': 'Shibin Alqanatir',
    'شبين الكوم': 'Shibin Alkum',
    'شربين': 'Shirbin',
    'شرم الشيخ': 'Sharm Alshaykh',
    'صدفا': 'Sudfan',
    'طابا': 'Taba',
    'طامية': 'Tamiatan',
    'طلخا': 'Talakhan',
    'طما': 'Tama',
    'طنطا - حي اول': 'Tanta - Hay Awl',
    'طنطا - حي ثاني': 'Tantan - Hayun Thani',
    'طهطا': 'Tahta',
    'طوخ': 'Tukh',
    'عابدين': 'Eabidin',
    'عتاقة': 'Eataqa',
    'عين حلوان': 'Eayn Hulwan',
    'عين شمس': 'Eayn Shams',
    'غرب القاهرة': 'Gharb Alqahira',
    'فارسكور': 'Fariskur',
    'فاقوس': 'Faqus',
    'فايد': 'Fayd',
    'فرشوط': 'Firshawt',
    'فوة': 'Fw',
    'قطور': 'Qatuwr',
    'قفط': 'Qift',
    'قلين': 'Qiliyn',
    'قليوب': 'Qalyub',
    'قنا': 'Qana',
    'قوص': 'Qus',
    'قوصية': 'Qusia',
    'قويسنا': 'Quisuna',
    'كفر الدوار': 'Kafr Aldawaar',
    'كفر الزيات': 'Kafar Alzayaat',
    'كفر الشيخ': 'Kafar Alshaykh',
    'كفر سعد': 'Kafar Saed',
    'كفر شكر': 'Kafar Shakr',
    'كفر صقر': 'Kafar Saqr',
    'كوم امبو': 'Kum Ambu',
    'كوم حمادة': 'Kum Hamada',
    'مدينة السادات': 'Alsaadat',
    'مدينة المعادي': 'Almaeadi',
    'مدينة ناصر': 'Nasir',
    'مدينة نصر - شرق': 'Nasr - Sharq',
    'مدينة نصر - غرب': 'Nasr - Gharb',
    'مرسي علم': 'Mursi Ealam',
    'مركز الجيزة': 'Markaz Aljiza',
    'مركز ومدينة اطفيح': 'Markaz Wamadinat Atfih',
    'مركز ومدينة الصف': 'Markaz Wamadinat Alsafi',
    'مشتول السوق': 'Mashtul Alsuwq',
    'مصر الجديدة': 'Misr Aljadida',
    'مصر القديمة': 'Misr Alqadima',
    'مطاي': 'Matay',
    'مطروح': 'Matruh',
    'مطوبس': 'Mutwbis',
    'مغاغة': 'Mughaghatan',
    'ملوي': 'Milwi',
    'منشاة ناصر': 'Munshaat Nasir',
    'منفلوط': 'Munfalut',
    'منوف': 'Munuf',
    'منيا القمح': 'Minya Alqamh',
    'منية النصر': 'Minyat Alnasr',
    'ميت غمر': 'Mayt Ghamar',
    'نبروه': 'Nabaruh',
    'نجع المهيدات': 'Naje Almahidat',
    'نجع حمادي': 'Naje Hamaadi',
    'نصر النوبة': 'Nasr Alnnwba',
    'نقادة': 'Nuqada',
    'ههيا': 'Hahyana',
    'وادي النطرون': 'Wadi Alnutrun',
    'وسط القاهرة': 'Wast Alqahira',
}


class AbCity(models.Model):
    _inherit = "ab_city"

    @api.depends("name")
    @api.depends_context("formatted_display_name", "lang")
    def _compute_display_name(self):
        super()._compute_display_name()

        lang = (self.env.context.get("lang") or "").lower()
        if not lang.startswith("en"):
            return

        for record in self:
            en_name = CITY_AR_TO_EN.get((record.name or "").strip())
            if en_name:
                record.display_name = en_name
