def _table_exists(cr, table_name):
    cr.execute("SELECT to_regclass(%s)", (table_name,))
    return bool(cr.fetchone()[0])


def migrate(cr, version):
    if not _table_exists(cr, "ab_hr_job"):
        return

    cr.execute(
        """
        CREATE TABLE IF NOT EXISTS ab_required_job (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR NOT NULL,
            job_id INTEGER NOT NULL,
            is_publish BOOLEAN DEFAULT TRUE,
            create_uid INTEGER,
            create_date TIMESTAMP,
            write_uid INTEGER,
            write_date TIMESTAMP
        )
        """
    )

    cr.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS ab_required_job_job_id_uniq
        ON ab_required_job (job_id)
        """
    )

    cr.execute(
        """
        INSERT INTO ab_required_job
            (id, name, job_id, is_publish, create_uid, create_date, write_uid, write_date)
        SELECT
            j.id,
            j.name,
            j.id,
            TRUE,
            1,
            NOW() AT TIME ZONE 'UTC',
            1,
            NOW() AT TIME ZONE 'UTC'
        FROM ab_hr_job j
        LEFT JOIN ab_required_job r ON r.job_id = j.id
        WHERE r.id IS NULL
        ON CONFLICT (id) DO NOTHING
        """
    )

    cr.execute(
        """
        INSERT INTO ab_required_job
            (name, job_id, is_publish, create_uid, create_date, write_uid, write_date)
        SELECT
            j.name,
            j.id,
            TRUE,
            1,
            NOW() AT TIME ZONE 'UTC',
            1,
            NOW() AT TIME ZONE 'UTC'
        FROM ab_hr_job j
        LEFT JOIN ab_required_job r ON r.job_id = j.id
        WHERE r.id IS NULL
        """
    )

    if _table_exists(cr, "ab_hr_application"):
        cr.execute(
            """
            UPDATE ab_hr_application a
            SET job_id = r.id
            FROM ab_required_job r
            WHERE a.job_id = r.job_id
            """
        )

    if _table_exists(cr, "ab_hr_job_post"):
        cr.execute(
            """
            UPDATE ab_hr_job_post p
            SET job_id = r.id
            FROM ab_required_job r
            WHERE p.job_id = r.job_id
            """
        )
