{
    'name': 'Accounting',
    'summary': 'Branch journals, controlled posting, openings and financial reports',
    'version': '19.0.2.0.0',
    'license': 'LGPL-3',
    'category': 'Accounting',
    'author': 'Abdin Pharmacies',
    'developer': 'hossam elsheikh',
    'application': True,
    'depends': ['base', 'mail', 'ab_store', 'ab_costcenter', 'report_xlsx'],
    'assets': {
        'web.assets_backend': [
            'ab_accounting/static/src/scss/x2many_tables.scss',
        ],
    },
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'data/sequence.xml',
        'views/configuration.xml',
        'views/journal.xml',
        'views/opening.xml',
        'views/reporting.xml',
        'report/templates.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'auto_install': False,
}
