{
    "name": "Abdin Sales Sync",
    "summary": "MAIN staging models for branch sales operations uploaded by AB Odoo Sync",
    "version": "19.0.1.3.0",
    "license": "LGPL-3",
    "category": "AbdinSupplyChain",
    "author": "Abdin Pharmacies",
    "developer": "hossam elsheikh",
    "application": True,
    "depends": ["ab_odoo_sync", "ab_users", "ab_hr", 'ab_customer', 'ab_contract', 'ab_product', 'ab_store',
                'abdin_et', 'ab_widgets'],
    "data": [
        "security/security_groups.xml",
        "security/record_rules.xml",
        "security/ir.model.access.csv",
        "data/sync_profiles.xml",
        "data/sync_profile_updates.xml",
        "data/sync_profiles_extra.xml",
        "views/ab_sales_sync_views.xml",
        "views/ab_sales_sync_extra_views.xml",
    ],
    "installable": True,
}
