{
    'name': 'Request Management',
    'version': '19.0.1.1.0',
    'license': 'LGPL-3',
    'category': 'AbdinSupplyChain',
    'application': True,
    'depends': ['base', 'mail', 'web', 'ab_hr'],
    'data': [
        'security/security_groups.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'data/ab_request_sequence.xml',
        'views/ab_request_dashboard_views.xml',
        'views/ab_request_type_views.xml',
        'views/ab_request_ticket_views.xml',
        'views/ab_request_followup_wizard_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ab_request_management/static/src/js/ab_request_dashboard.js',
            'ab_request_management/static/src/js/ab_request_list_renderer_patch.js',
            'ab_request_management/static/src/js/ab_request_state_widgets.js',
            'ab_request_management/static/src/js/ab_request_kanban_view.js',
            'ab_request_management/static/src/js/ab_request_summary_widget.js',
            'ab_request_management/static/src/xml/ab_request_dashboard.xml',
            'ab_request_management/static/src/xml/ab_request_list_renderer.xml',
            'ab_request_management/static/src/xml/ab_request_state_widgets.xml',
            'ab_request_management/static/src/xml/ab_request_summary_widget.xml',
            'ab_request_management/static/src/xml/ab_request_form_status_indicator.xml',
            'ab_request_management/static/src/scss/ab_request_management.scss',
        ],
    },
    'installable': True,
    'icon': '/ab_request_management/static/description/1.svg'
}
