{
    'name': 'Requests and Complaints',
    'version': '19.0.1.5.1',
    'license': 'LGPL-3',
    'category': 'AbdinSupplyChain',
    'application': True,
    'depends': ['base', 'mail', 'web', 'ab_hr', 'ab_core_ui'],
    'data': [
        'security/security_groups.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'data/ab_request_sequence.xml',
        'data/ab_request_cron.xml',
        'views/ab_request_dashboard_views.xml',
        'views/ab_request_type_views.xml',
        'views/ab_request_ticket_views.xml',
        'views/ab_request_followup_wizard_views.xml',
        'views/ab_request_website_views.xml',
        'views/customer_request_templates.xml',
        'views/menus.xml',
    ],
    'assets': {
        'ab_request_management.assets_public_request': [
            'ab_core_ui/static/src/scss/core_ui_variables.scss',
            'ab_core_ui/static/src/scss/core_ui_components.scss',
            'ab_request_management/static/src/scss/customer_request_form.scss',
        ],
        'web.assets_backend': [
            'ab_request_management/static/src/js/ab_request_dashboard.js',
            'ab_request_management/static/src/js/ab_request_list_controller_patch.js',
            'ab_request_management/static/src/js/ab_request_list_renderer_patch.js',
            'ab_request_management/static/src/js/ab_request_state_widgets.js',
            'ab_request_management/static/src/js/ab_request_kanban_view.js',
            'ab_request_management/static/src/js/ab_request_summary_widget.js',
            'ab_request_management/static/src/xml/ab_request_dashboard.xml',
            'ab_request_management/static/src/xml/ab_request_list_controller.xml',
            'ab_request_management/static/src/xml/ab_request_list_renderer.xml',
            'ab_request_management/static/src/xml/ab_request_state_widgets.xml',
            'ab_request_management/static/src/xml/ab_request_summary_widget.xml',
            'ab_request_management/static/src/xml/ab_request_form_status_indicator.xml',
            'ab_request_management/static/src/scss/ab_request_management.scss',
        ],
    },
    'installable': True,
    'icon': '/ab_request_management/static/description/1.svg'
}
