{
    'name': 'Supplier Claim Cycle',
    'version': '19.0.4.0.0',
    'description': 'Supplier claims with sequential reviews, department decisions, and audited Secretarial closure.',
    'license': 'LGPL-3',
    'category': 'AbdinSupplyChain',
    'author': 'Abdin Pharmacies',
    'developer': 'Alhassan Hossny',
    'application': True,
    'depends': ['base', 'mail', 'web', 'ab_costcenter'],
    'data': [
        'security/groups.xml',
        'security/record_rules.xml',
        'security/costcenter_rules.xml',
        'security/ir.model.access.csv',
        'views/menus.xml',
        'views/ab_supplier_claim_cycle.xml',
        'views/supplier_terms.xml',
        'views/claim_design.xml',
    ],
    'assets': {'web.assets_backend': [
        'ab_supplier_claim_cycle/static/src/scss/claim_design.scss',
    ]},
    'installable': True,
}
