{
    'name': 'Abdin Purchase',
    'license': 'LGPL-3',
    'category': 'AbdinSupplyChain',
    'application': True,
    'depends': ['base', 'mail', 'abdin_et',
                'ab_accounting', 'ab_product_source', 'ab_store', 'ab_supplier',
                'ab_inventory'],
    'data': [
        'security/security_groups.xml',
        'security/record_rules_purchase_header.xml',
        'security/record_rules_purchase_notice_header.xml',
        'security/record_rules_purchase_claim.xml',
        'security/ir.model.access.csv',
        'views/menus.xml',
        'views/ab_product_supplier_origin.xml',
        'views/ab_purchase_header.xml',
        'views/ab_purchase_line.xml',
        'views/ab_purchase_notice_header.xml',
        'views/ab_purchase_notice_line.xml',
        'views_accounting/ab_purchase_claim.xml',
        'views_accounting/ab_accounting_je_inherit.xml',
        'views_accounting/ab_purchase_report_wizard.xml',
        'views_accounting/templates_balance_dist.xml',
        'views_accounting/pdf_supplier_balances.xml',
        'views_accounting/xlsx_supplier_balances.xml',
        # 'views_accounting/ab_supplier_inherit.xml',
        # 'views_accounting/ab_purchase_claim_line.xml',
        # 'views_accounting/ab_purchase_claim_dist_line.xml',
    ],

}
