{
    'name': 'Abdin Purchase',
    'version': '19.0.1.0.0',
    'license': 'LGPL-3',
    'category': 'AbdinSupplyChain',
    'author': 'Abdin Pharmacies',
    'developer': 'emadco88',
    'application': True,
    'depends': [
        'base',
        'mail',
        'abdin_et',
        'ab_product_source',
        'ab_store',
        'ab_supplier',
        'ab_inventory',
        'ab_taxes',
    ],
    'data': [
        'security/security_groups.xml',
        'security/record_rules_purchase_header.xml',
        'security/record_rules_purchase_notice_header.xml',
        'security/record_rules_data_entry.xml',
        'security/ir.model.access.csv',
        'views/menus.xml',
        'views/ab_purchase_dashboard.xml',
        'views/ab_purchase_header.xml',
        'views/ab_purchase_line.xml',
        'views/ab_purchase_notice_header.xml',
        'views/ab_purchase_notice_line.xml',
        'views/ab_purchase_links_views.xml',
        'views/ab_purchase_entry_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ab_purchase/static/src/dashboard/purchase_dashboard.js',
            'ab_purchase/static/src/dashboard/purchase_dashboard.xml',
            'ab_purchase/static/src/dashboard/purchase_dashboard.scss',
            'ab_purchase/static/src/entry/purchase_entry.js',
            'ab_purchase/static/src/entry/purchase_entry.xml',
            'ab_purchase/static/src/entry/purchase_entry.scss',
        ],
    },
    'installable': True,
    'auto_install': False,
}
