{
    "name": "Abdin Sales Reporting Mirror",
    "summary": "Passive MAIN-side mirrors of branch sales data",
    "version": "19.0.2.0.0",
    "license": "LGPL-3",
    "category": "AbdinSupplyChain",
    "author": "Abdin Pharmacies",
    "developer": "emadco88",
    "application": True,
    "depends": [
        "ab_users",
        "ab_hr",
        "ab_customer",
        "ab_contract",
        "ab_product",
        "ab_store",
        "abdin_et",
        "ab_widgets",
    ],
    "data": [
        "security/groups_sales.xml",
        "security/rules_sales.xml",
        "security/ir.model.access.csv",
        "views/sales_mirror_views.xml",
        "views/sales_mirror_extra_views.xml",
    ],
    "installable": True,
}
