{
    'name': 'Abdin Sales',
    'version': '19.0.1.0.0',
    'license': 'LGPL-3',
    'category': 'AbdinSupplyChain',
    'application': True,
    'depends': ['base', 'ab_customer', 'ab_contract', 'ab_product', 'ab_store', 'ab_eplus_connect',
                'abdin_et', 'ab_widgets'],
    'data': [
        'data/ir_cron.xml',
        'security/groups_sales.xml',
        'security/rules_sales.xml',
        'security/ir.model.access.csv',
        'views/menus.xml',
        'views/pos_action.xml',
        'views/bill_wizard_action.xml',
        'views/bill_wizard_print_templates.xml',
        'views/bill_wizard_print_a4_templates.xml',
        'views/ab_sales_return.xml',
        'views/ab_sales_return_line.xml',
        'views/ab_sales_return_server_action.xml',
        'views/sales_header.xml',
        'views/ab_sales_unavailable_reason_required_views.xml',
        'views/sales_line.xml',
        'views/ab_sales_unavailable_wizard_line_views.xml',
        'views/ab_sales_configuration.xml',
        'views/ab_printer_views.xml',
        'views/ab_sales_inventory.xml',
        'views/ab_sales_per_day.xml',
        'views/ab_replica_db_inherit.xml',
        'views/ab_sales_branch_rpc_config_views.xml',
        'views/ab_sales_callcenter_rpc_log_views.xml',
        'views/ab_product_metadata_views.xml',
        'views/ab_product_inherit.xml',
        'views/ab_product_balance_wizard.xml',
        'views/product_store_balance_qweb.xml',
        'views/ab_sales_unavailable_wizard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ab_sales/static/src/js/many2one_search_more_f1.js',
            'ab_sales/static/src/dashboard/**/*.js',
            'ab_sales/static/src/dashboard/**/*.xml',
            'ab_sales/static/src/dashboard/**/*.scss',
            'ab_sales/static/src/add_products/**/*.js',
            'ab_sales/static/src/add_products/**/*.xml',
            'ab_sales/static/src/add_products/**/*.scss',
            'ab_sales/static/src/bill_wizard/**/*.js',
            'ab_sales/static/src/bill_wizard/**/*.xml',
            'ab_sales/static/src/bill_wizard/**/*.scss',
            'ab_sales/static/src/pos/**/*.js',
            'ab_sales/static/src/pos/**/*.xml',
            'ab_sales/static/src/pos/**/*.scss',
            'ab_sales/static/src/sales_return/**/*.js',
            'ab_sales/static/src/sales_return/**/*.xml',
            'ab_sales/static/src/invoice_exclusions/**/*.js',
            'ab_sales/static/src/invoice_exclusions/**/*.xml',
        ],
    },

    'installable': True,
}
