{
    "name": "AB Sync Test Models",
    "summary": "Relational source models for AB Odoo Sync simulation",
    "version": "19.0.1.1.0",
    "license": "LGPL-3",
    "category": "Tools",
    "author": "Abdin Pharmacies",
    "developer": "Alhassan Hossny",
    "application": True,
    "depends": ["base", "ab_odoo_sync_upload", "ab_customer"],
    "data": [
        "security/security_groups.xml",
        "security/record_rules.xml",
        "security/customer_reference_rules.xml",
        "security/ir.model.access.csv",
        "security/customer_reference_access.xml",
        "data/sync_upload_sources.xml",
        "views/ab_test_views.xml",
        "views/ab_test_customer_reference_views.xml",
    ],
    "installable": True,
}
