{
    "name": "Smart Security Manager",
    "version": "19.0.1.0.0",
    "license": "LGPL-3",
    "author": "Abdin",
    "category": "Tools",
    "summary": "Dynamic role, ACL, and field security management",
    "application": True,
    "icon": "ab_smart_security_manager/static/description/admin-icon.svg",
    "depends": ["base", "web"],
    "post_init_hook": "post_init_hook",
    "data": [
        "security/ir.model.access.csv",
        "security/security_groups.xml",
        "views/ab_security_role_views.xml",
        "views/ab_security_model_access_views.xml",
        "views/ab_security_field_access_views.xml",
        "views/res_users_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
}
