{
    "name": "Abdin eCommerce Storefront",
    "summary": "Abdin-branded storefront for native Odoo eCommerce",
    "version": "19.0.1.0.0",
    "license": "LGPL-3",
    "category": "Website/eCommerce",
    "author": "Abdin Pharmacies",
    "developer": "Mohamed Fawzy",
    "depends": [
        "ab_website",
        "ab_website_admin_content",
        "ab_website_sale_product",
        "mail",
        "portal",
        "sale_stock",
        "website_sale_wishlist",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "security/business_partnership.xml",
        "data/storefront_catalog.xml",
        "data/prescription_sequence.xml",
        "views/category_icons.xml",
        "views/avatar.xml",
        "views/auth.xml",
        "views/prescription_order_views.xml",
        "views/call_center_order_views.xml",
        "views/layout.xml",
        "views/contact_message_views.xml",
        "views/business_partnership_views.xml",
        "views/contact_templates.xml",
        "views/homepage.xml",
        "views/shop.xml",
        "views/product.xml",
        "views/cart.xml",
        "views/portal.xml",
        "views/sale_order_report.xml",
        "views/prescription_order_templates.xml",
        "views/empty_states.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ab_ecommerce_storefront/static/src/js/call_center_order_workspace.js",
            "ab_ecommerce_storefront/static/src/xml/call_center_order_workspace.xml",
            "ab_ecommerce_storefront/static/src/scss/call_center_order_workspace.scss",
        ],
        "web.assets_frontend": [
            "ab_ecommerce_storefront/static/src/js/hero_carousel.js",
            "ab_ecommerce_storefront/static/src/js/auth.js",
            "ab_ecommerce_storefront/static/src/js/avatar_picker.js",
            "ab_ecommerce_storefront/static/src/js/current_location.js",
            "ab_ecommerce_storefront/static/src/js/logo_motion.js",
            "ab_ecommerce_storefront/static/src/js/sticky_shop_nav.js",
            "ab_ecommerce_storefront/static/src/js/support_widget.js",
            "ab_ecommerce_storefront/static/src/js/search_typewriter.js",
            "ab_ecommerce_storefront/static/src/js/search_autocomplete_clear.js",
            "ab_ecommerce_storefront/static/src/js/shop_category_accordion.js",
            "ab_ecommerce_storefront/static/src/js/price_range_guard.js",
            "ab_ecommerce_storefront/static/src/js/cart_selection.js",
            "ab_ecommerce_storefront/static/src/js/prescription_order.js",
            "ab_ecommerce_storefront/static/src/js/business_partnership.js",
            "ab_ecommerce_storefront/static/src/js/payment_status.js",
            "ab_ecommerce_storefront/static/src/js/quantity_motion.js",
            "ab_ecommerce_storefront/static/src/js/stock_warning.js",
            "ab_ecommerce_storefront/static/src/js/product_card.js",
            "ab_ecommerce_storefront/static/src/js/animated_price.js",
            "ab_ecommerce_storefront/static/src/js/product_image_zoom.js",
            "ab_ecommerce_storefront/static/src/scss/typography.scss",
            "ab_ecommerce_storefront/static/src/scss/storefront.scss",
            "ab_ecommerce_storefront/static/src/scss/auth_fields.scss",
            "ab_ecommerce_storefront/static/src/scss/contact.scss",
        ],
    },
    "installable": True,
    "application": False,
}
