{
    "name": "Abdin Website Sale Products",
    "summary": "Sync Abdin products into Odoo eCommerce products",
    "version": "19.0.1.0.0",
    "license": "LGPL-3",
    "author": "Abdin Pharmacies",
    "category": "Website",
    "depends": ["website_sale_stock", "ab_product", "ab_eplus_connect"],
    "data": [
        "security/security_sync_groups.xml",
        "security/ir.model.access.csv",
        "data/server_actions.xml",
        "security/sync_action_security.xml",
        "data/ir_cron.xml",
        "views/add_many_by_codes_views.xml",
        "views/eplus_stock_snapshot_views.xml",
        "views/ab_product_views.xml",
        "views/product_template_views.xml",
        "views/website_sale_menus.xml",
        "views/ab_product_kanban_views.xml",
        "views/ab_product_professional_views.xml",
        "sync_images_views.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "ab_website_sale_product/static/src/xml/stock_availability.xml",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
