VERIFIED_AT = "2026-09-28"


def source(name, domain, official, api="", bulk="", license="Review required", **kw):
    return dict(name=name, provider_type=kw.pop("provider_type", "DATA_SOURCE"), domain=domain,
                official_url=official, api_url=api, bulk_url=bulk, license=license,
                terms_url=kw.pop("terms_url", official), authentication=kw.pop("authentication", "None for public data"),
                current_limits=kw.pop("current_limits", "No guaranteed allowance; configure a conservative local cap."),
                commercial_use=kw.pop("commercial_use", "review"), authority=kw.pop("authority", "secondary"),
                market_relevance=kw.pop("market_relevance", "limited"), scope=kw.pop("scope", "product"),
                identifiers=kw.pop("identifiers", "source_id,name"), last_verified_at=VERIFIED_AT, **kw)


CATALOG = {
    "eda_eddb": source("Egyptian Drug Authority EDDB", "drug,cosmetic,supplement",
        "https://edaegypt.gov.eg/en/services/databases/", authority="regulatory", market_relevance="egypt",
        mode="manual", identifiers="registration,name", current_limits="Official search/manual verification; no documented public bulk API verified."),
    "egypt_a": source("Egyptian Drug Database Dataset A", "drug",
        "https://github.com/karem505/egyptian-drug-database",
        bulk="https://raw.githubusercontent.com/karem505/egyptian-drug-database/main/data/egyptian-drugs.csv",
        license="CC0 (publisher declaration)", commercial_use="allowed", market_relevance="egypt",
        current_limits="Public CSV/JSON release; Arabic names are transliterated search aliases."),
    "egypt_b": source("Egyptian Drug Database Dataset B", "drug",
        "https://github.com/mahmoudfalous/eg-drugs",
        bulk="https://raw.githubusercontent.com/mahmoudfalous/eg-drugs/main/data/eg_drugs.csv",
        license="Noncommercial; separate commercial permission required", commercial_use="permission", market_relevance="egypt",
        current_limits="Public release. Generated usage summaries and safety flags remain unverified context."),
    "dailymed": source("DailyMed", "drug", "https://dailymed.nlm.nih.gov/dailymed/spl-resources-all-drug-labels.cfm",
        api="https://dailymed.nlm.nih.gov/dailymed/services/v2",
        bulk="https://dailymed.nlm.nih.gov/dailymed/spl-resources-all-drug-labels.cfm",
        license="NLM terms; label content rights require review", authority="official", identifiers="source_id,ndc,rxcui,name",
        current_limits="Multipart full SPL ZIP releases and daily/weekly/monthly updates; choose a release download URL."),
    "openfda": source("openFDA Drug Label Data", "drug", "https://open.fda.gov/apis/drug/label/",
        api="https://api.fda.gov/drug/label.json", bulk="https://api.fda.gov/download.json",
        license="Public domain / openFDA terms", commercial_use="allowed", authority="official",
        identifiers="source_id,ndc,rxcui,name", authentication="Optional api_key query parameter",
        terms_url="https://open.fda.gov/terms/", current_limits="240 requests/minute; 1,000/day without key; 120,000/day with key. Bulk preferred."),
    "fda_ndc": source("FDA NDC", "drug", "https://open.fda.gov/apis/drug/ndc/",
        api="https://api.fda.gov/drug/ndc.json", bulk="https://api.fda.gov/download.json",
        license="Public domain / openFDA terms", commercial_use="allowed", authority="official",
        identifiers="source_id,ndc,rxcui,name", authentication="Optional api_key query parameter",
        terms_url="https://open.fda.gov/terms/", current_limits="Same openFDA account/IP quotas; NDC listing is not approval."),
    "rxnorm": source("RxNorm", "drug", "https://www.nlm.nih.gov/research/umls/rxnorm/overview.html",
        api="https://rxnav.nlm.nih.gov/REST", bulk="https://www.nlm.nih.gov/research/umls/licensedcontent/rxnormfiles.html",
        license="UMLS; source vocabulary restrictions apply", authority="official", scope="normalization",
        identifiers="source_id,rxcui,ndc,name", authentication="Public RxNav; UTS license for full releases",
        current_limits="Monthly full release plus ordered weekly RRF updates; public prescribable subset available."),
    "drugcentral": source("DrugCentral", "drug", "https://drugcentral.org/download",
        bulk="https://drugcentral.org/download", license="Creative Commons; verify selected release terms",
        scope="ingredient", identifiers="source_id,cas,inchi,name", terms_url="https://drugcentral.org/privacy"),
    "dsld": source("NIH Dietary Supplement Label Database", "supplement", "https://dsld.od.nih.gov/api-guide",
        api="https://dsldapi.od.nih.gov/dsld/v9", bulk="https://dsld.od.nih.gov/label-download",
        license="CC0 1.0", commercial_use="allowed", authority="official", identifiers="source_id,gtin,name",
        terms_url="https://dsldapi.od.nih.gov/", current_limits="Bulk label downloads preferred; no guaranteed unlimited API quota."),
    "openbeautyfacts": source("Open Beauty Facts", "cosmetic", "https://world.openbeautyfacts.org/data",
        api="https://world.openbeautyfacts.org/api/v2/product", bulk="https://world.openbeautyfacts.org/data",
        license="ODbL; attribution and share-alike; images separate", authority="community", identifiers="gtin,name"),
    "cosing": source("CosIng", "cosmetic", "https://single-market-economy.ec.europa.eu/sectors/cosmetics/cosmetic-ingredient-database_en",
        scope="ingredient", mode="manual", identifiers="cas,ec,inci,name",
        current_limits="Official ingredient search/export; no documented public API verified. Inventory entry is not an approval."),
    "cir": source("Cosmetic Ingredient Review", "cosmetic", "https://cir-reports.cir-safety.org/",
        scope="ingredient", mode="manual", identifiers="cas,inci,name",
        current_limits="Manual ingredient review with scientific references; no public bulk API verified."),
    "openfoodfacts": source("Open Food Facts", "food", "https://openfoodfacts.github.io/openfoodfacts-server/api/",
        api="https://world.openfoodfacts.org/api/v2/product", bulk="https://world.openfoodfacts.org/data",
        license="ODbL; attribution and share-alike; images separate", authority="community", identifiers="gtin,name",
        current_limits="Product reads 100/minute; searches 10/minute. Bulk recommended for large collections."),
    "openproductsfacts": source("Open Products Facts", "general", "https://world.openproductsfacts.org/data",
        api="https://world.openproductsfacts.org/api/v2/product", bulk="https://world.openproductsfacts.org/data",
        license="ODbL; attribution and share-alike; images separate", authority="community", identifiers="gtin,name"),
    "usda_fdc": source("USDA FoodData Central", "food", "https://fdc.nal.usda.gov/api-guide/",
        api="https://api.nal.usda.gov/fdc/v1", bulk="https://fdc.nal.usda.gov/download-datasets/",
        license="Public domain / CC0", commercial_use="allowed", authority="official", identifiers="source_id,gtin,name",
        authentication="data.gov API key for API; public bulk files", current_limits="Default 1,000 requests/hour/IP; bulk has no API-key requirement."),
    "pubchem": source("PubChem", "drug,cosmetic,supplement,food", "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
        api="https://pubchem.ncbi.nlm.nih.gov/rest/pug", bulk="https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/",
        scope="ingredient", identifiers="source_id,cas,inchi,name", authority="scientific",
        license="Contributor-specific rights; attribution required", current_limits="At most 5 requests/second; dynamic throttling also applies."),
    "chembl": source("ChEMBL", "drug", "https://chembl.gitbook.io/chembl-interface-documentation/web-services",
        api="https://www.ebi.ac.uk/chembl/api/data", bulk="https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/",
        license="CC BY-SA 3.0", scope="ingredient", authority="scientific", identifiers="source_id,inchi,name"),
    "gs1": source("GS1 Verified by GS1", "drug,cosmetic,supplement,food,general", "https://www.gs1.org/services/verified-by-gs1",
        provider_type="BARCODE_LOOKUP", mode="manual", identifiers="gtin", authority="identifier",
        terms_url="https://www.gs1.org/docs/verified-by-gs1/public-verified-by-gs1-tou.pdf",
        current_limits="Public UI: 30 single GTIN queries/24h. Automated/bulk access requires separate service terms."),
    "upcitemdb": source("UPCitemdb", "drug,cosmetic,supplement,food,general", "https://www.upcitemdb.com/wp/docs/main/development/plan/",
        api="https://api.upcitemdb.com/prod/trial/lookup", provider_type="BARCODE_LOOKUP", identifiers="gtin",
        current_limits="Free trial: 100 combined requests/day; burst limits also apply."),
    "openfda_cosmetic_event": source("openFDA Cosmetic Event Reports", "cosmetic", "https://open.fda.gov/apis/cosmetic/event/",
        api="https://api.fda.gov/cosmetic/event.json", bulk="https://api.fda.gov/download.json",
        provider_type="SAFETY_REGULATORY", scope="safety", authority="official", license="Public domain / openFDA terms",
        commercial_use="allowed", authentication="Optional api_key query parameter", current_limits="Shares openFDA limits. Internal adverse-event context only."),
    "ready_api": source("Ready API Trial Enrichment", "drug", "https://ready-api.vercel.app/apis/drugs-eg",
        api="https://ready-api.vercel.app/api/drugs-eg", authentication="Bearer API key", market_relevance="egypt",
        current_limits="Finite account/trial allowance; configure from current account. Existing paginated cache retained."),
}


def ai(name, url, api, model, **kw):
    entry = source(name, "drug,cosmetic,supplement,food,general", url, api=api,
                   authentication="Bearer API key", license="Service and selected model terms", **kw)
    entry.update(provider_type="AI_GENERATOR", scope="generation", model=model)
    return entry


CATALOG.update({
    "google_gemini": ai("Google Gemini", "https://ai.google.dev/gemini-api/docs/models",
        "https://generativelanguage.googleapis.com/v1beta", "gemini-3.5-flash",
        current_limits="RPM/RPD/TPM depend on model/project/tier; read current AI Studio limits.", terms_url="https://ai.google.dev/gemini-api/terms"),
    "groq": ai("Groq", "https://console.groq.com/docs/models", "https://api.groq.com/openai/v1", "",
        current_limits="Select an available model via /models; account-specific RPM/RPD/TPM/TPD.", terms_url="https://console.groq.com/docs/deprecations"),
    "openrouter": ai("OpenRouter", "https://openrouter.ai/docs/quickstart", "https://openrouter.ai/api/v1", "openrouter/free",
        current_limits="Free models and quotas vary; /models and /key expose availability and account limits.", terms_url="https://openrouter.ai/terms"),
    "huggingface": ai("Hugging Face", "https://huggingface.co/docs/inference-providers/index", "https://router.huggingface.co/v1", "",
        current_limits="Finite monthly hosted credits; choose an available provider/model.", terms_url="https://huggingface.co/docs/inference-providers/en/pricing"),
    "alibaba_qwen": ai("Alibaba Qwen / Model Studio", "https://www.alibabacloud.com/help/en/model-studio/what-is-model-studio",
        "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", "qwen-plus",
        current_limits="Region/model/account quotas; new Singapore trials expire. Enable Free Quota Only in console.",
        terms_url="https://www.alibabacloud.com/help/en/model-studio/new-free-quota"),
    "cohere": ai("Cohere", "https://docs.cohere.com/v2/reference/chat", "https://api.cohere.com/v2", "command-a-03-2025",
        current_limits="Trial: 20 chat requests/minute, 1,000 calls/month; evaluation terms.", terms_url="https://docs.cohere.com/v2/docs/rate-limits"),
    "cloudflare": ai("Cloudflare Workers AI", "https://developers.cloudflare.com/workers-ai/get-started/rest-api/",
        "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai", "@cf/meta/llama-3.1-8b-instruct",
        current_limits="10,000 neurons/day free; configure model unit costs and account budget.", terms_url="https://developers.cloudflare.com/workers-ai/platform/pricing/"),
    "local_ai": ai("Local AI", "https://docs.vllm.ai/en/latest/serving/openai_compatible_server/", "http://localhost:8000/v1", "",
        current_limits="Local hardware capacity; no external free allowance.", commercial_use="review"),
    "openai": ai("OpenAI (existing optional provider)", "https://platform.openai.com/docs/api-reference/chat", "https://api.openai.com/v1", "gpt-4.1-mini",
        current_limits="Existing paid provider retained; configure account limits."),
    "other": ai("Other compatible provider", "", "", "", current_limits="Administrator-supplied endpoint and terms."),
})
CATALOG["local_ai"].update(provider_type="LOCAL_MODEL", authentication="Optional local bearer token")
