{
    "name": "Sales Dashboard",
    "description": "Management sales dashboard backed by BConnect / E-Plus reporting data.",
    "version": "19.0.1.0.0",
    "license": "LGPL-3",
    "category": "AbdinSupplyChain",
    "author": "Abdin Pharmacies",
    "developer": "Alhassan Hossny",
    "application": True,
    "depends": ["base", "web", "ab_core_ui", "ab_eplus_connect", "ab_store", "ab_product"],
    "data": [
        "security/security_groups.xml",
        "security/record_rules.xml",
        "security/ir.model.access.csv",
        "views/menus.xml",
        "data/sales_dashboard_sequence.xml",
        "data/sales_dashboard_telemetry_cron.xml",
        "views/sales_dashboard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ab_sales_dashboard/static/src/scss/sales_dashboard.scss",
            "ab_sales_dashboard/static/src/scss/sales_report.scss",
            "ab_sales_dashboard/static/src/scss/sales_reports_library.scss",
            "ab_sales_dashboard/static/src/scss/sales_reconciliation_console.scss",
            "ab_sales_dashboard/static/src/js/utils/formatters.js",
            "ab_sales_dashboard/static/src/js/components/pct_bar.js",
            "ab_sales_dashboard/static/src/js/components/theme_toggle.js",
            "ab_sales_dashboard/static/src/js/components/kpi_card.js",
            "ab_sales_dashboard/static/src/js/components/donut_chart.js",
            "ab_sales_dashboard/static/src/js/components/bar_chart.js",
            "ab_sales_dashboard/static/src/js/components/ranking_table.js",
            "ab_sales_dashboard/static/src/js/components/data_table.js",
            "ab_sales_dashboard/static/src/js/components/loading_skeleton.js",
            "ab_sales_dashboard/static/src/js/sales_dashboard_action.js",
            "ab_sales_dashboard/static/src/js/sales_report_action.js",
            "ab_sales_dashboard/static/src/js/sales_report_list_controller.js",
            "ab_sales_dashboard/static/src/js/sales_reconciliation_controller.js",
        ],
    },
    "installable": True,
}
