{
    "name": "AB Odoo Sync Mapping",
    "summary": "Receive branch uploads and apply reporting mappings",
    "version": "19.0.1.3.0",
    "license": "LGPL-3",
    "category": "Tools",
    "author": "Abdin Pharmacies",
    "developer": "emadco88",
    "website": "https://www.abdinpharmacies.com",
    "application": True,
    "depends": ["ab_odoo_sync", "queue_job"],
    "data": [
        "security/ir.model.access.csv",
        "data/queue_jobs.xml",
        "data/crons.xml",
        "views/mapping_views.xml",
        "views/configuration_views.xml",
        "data/configuration_todo.xml",
    ],
    "installable": True,
}
