{
    'name': 'نظام حسابات المرتبات (Payroll Accounting Module)',
    'version': '1.1',
    'category': 'Human Resources',
    'summary': 'إدارة المرتبات والحضور بنظم احتساب متعددة',
    'depends': ['base', 'hr', 'ab_hr'],
    'data': [
        'security/ir.model.access.csv',
        'views/actions.xml',
        'views/menu.xml',
        'wizard/payroll_excel_import_view.xml',
        'wizard/attendance_import_view.xml',
        'views/payroll_rule_view.xml',
        'views/payroll_period_view.xml',
        'views/salary_structure_view.xml',
        'views/attendance_view.xml',
        'views/deductions_view.xml',
        'views/payslip_view.xml',
        'views/allowance_view.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
