{
    "name": "SEO Optimization",
    "version": "19.0.1.0.0",
    "license": "LGPL-3",
    "category": "AbdinSupplyChain",
    "author": "Alhassan Hossny",
    "application": True,
    "depends": [
        "base",
        "mail",
        "website_sale",
        "ab_product",
        "ab_website_sale_product",
    ],
    "data": [
        "security/security_groups.xml",
        "security/record_rules.xml",
        "security/ir.model.access.csv",
        "views/menus.xml",
        "data/seo_assistant_data.xml",
        "data/seo_bulk_cron.xml",
        "views/product_seo_optimize_confirm_wizard_views.xml",
        "views/product_seo_views.xml",
        "views/product_seo_translation_views.xml",
        "views/product_seo_version_views.xml",
        "views/product_seo_publish_log_views.xml",
        "views/product_seo_match_views.xml",
        "views/product_seo_source_snapshot_views.xml",
        "views/product_seo_bulk_optimization_views.xml",
        "views/product_drug_data_views.xml",
        "views/drug_eg_import_dashboard_views.xml",
        "views/seo_assistant_views.xml",
    ],
    "assets": {
        "website.assets_editor": [
            "ab_website_seo_optimization/static/src/js/seo_dialog_ai_patch.js",
        ],
    },
    "installable": True,
}
