# -*- coding: utf-8 -*-
import logging
from datetime import datetime, time

from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError
from odoo.tools.sql import column_exists, rename_column

_logger = logging.getLogger(__name__)


class AbTransferHeader(models.Model):
    _name = "ab_transfer_header"
    _inherit = ["ab_eplus_connect"]
    _description = "ab_transfer_header"
    _order = "id desc"
    _rec_name = "display_name"

    display_name = fields.Char(
        string="Name",
        compute="_compute_display_name",
        store=True,
    )

    # SQL mapping:
    # stnh_id is generated by SQL Server Store_Trans_h identity

    from_store_id = fields.Many2one(
        "ab_store",
        string="From Store",
        domain=lambda self: self._get_allowed_source_store_domain(),
        default=lambda self: self._default_from_store_id(),
        required=True,
    )
    # stnh_f_Sto_id = from_store_id

    to_store_id = fields.Many2one(
        "ab_store",
        string="To Store",
        required=True,
    )
    # stnh_t_Sto_id = to_store_id

    user_id = fields.Many2one(
        "ab_costcenter",
        string="User",
        default=lambda self: self._default_user_id(),
        required=True,
        readonly=True,
    )
    # sec_insert_uid = user_id

    employee_delivery_id = fields.Many2one(
        "ab_costcenter",
        string="Delivery Employee",
    )
    # delivery_emp = employee_delivery_id

    notes = fields.Char(
        string="Notes",
    )
    # stnh_notes = notes

    selection = fields.Selection(
        [
            ("prepending", "Prepending"),
            ("pending", "Pending"),
            ("saved", "Saved"),
        ],
        string="Status",
        default="prepending",
        required=True,
        tracking=True,
    )
    # stnh_flag = selection (mapped later to SQL char value)

    line_ids = fields.One2many(
        "ab_transfer_line",
        "header_id",
        string="Lines",
    )

    items_count = fields.Integer(
        string="Items Count",
        compute="_compute_totals",
        store=True,
    )
    # stnh_no_items = items_count

    total_sell_price = fields.Float(
        string="Total Sell Price",
        digits=(16, 3),
        compute="_compute_totals",
        store=True,
    )
    # stnh_tot_sell_value = total_sell_price

    total_cost = fields.Float(
        string="Total Cost",
        digits=(16, 3),
        compute="_compute_totals",
        store=True,
    )
    # stnh_tot_cost_value = total_cost

    is_submitted = fields.Boolean(
        string="Submitted?",
        default=False,
        copy=False,
    )

    sent_at = fields.Datetime(
        string="Sent At",
        copy=False,
    )

    error_message = fields.Text(
        string="Error",
        copy=False,
    )

    company_id = fields.Many2one(
        "res.company",
        string="Company",
        default=lambda self: self.env.company,
        required=True,
    )

    def _auto_init(self):
        for old_name, new_name in {
            "sent_to_eplus": "is_submitted",
            "eplus_sent_at": "sent_at",
            "eplus_error_message": "error_message",
        }.items():
            if (
                    column_exists(self.env.cr, self._table, old_name)
                    and not column_exists(self.env.cr, self._table, new_name)
            ):
                rename_column(self.env.cr, self._table, old_name, new_name)
        return super()._auto_init()

    @api.model
    def _get_allowed_source_store_ids(self):
        try:
            replica_db = self.env["ab_replica_db"].sudo().get_current_from_config()
        except Exception:
            return []
        if not replica_db:
            return []
        return replica_db.allowed_sales_store_ids.filtered("allow_sale").ids

    @api.model
    def _get_allowed_source_store_domain(self):
        domain = [("allow_sale", "=", True)]
        store_ids = self._get_allowed_source_store_ids()
        if store_ids:
            domain.append(("id", "in", store_ids))
        return domain

    @api.model
    def _get_default_source_store(self):
        try:
            replica_db = self.env["ab_replica_db"].sudo().get_current_from_config()
        except Exception:
            return self.env["ab_store"].browse()
        if not replica_db or not replica_db.default_sales_store_id:
            return self.env["ab_store"].browse()
        store = replica_db.default_sales_store_id
        allowed_store_ids = self._get_allowed_source_store_ids()
        if store.allow_sale and (not allowed_store_ids or store.id in allowed_store_ids):
            return store
        return self.env["ab_store"].browse()

    @api.model
    def _default_from_store_id(self):
        store = self._get_default_source_store()
        return store.id if store else False

    @api.model
    def _default_user_id(self):
        if "ab_hr_employee" not in self.env.registry:
            return False
        employee = self.env["ab_hr_employee"].sudo().search(
            [
                ("user_id", "=", self.env.user.id),
                ("costcenter_id", "!=", False),
            ],
            limit=1,
        )
        return employee.costcenter_id.id if employee and employee.costcenter_id else False

    @api.depends("from_store_id", "to_store_id")
    def _compute_display_name(self):
        for rec in self:
            if rec.id:
                rec.display_name = _("Transfer %s") % rec.id
            else:
                rec.display_name = _("New Transfer")

    @api.depends("line_ids", "line_ids.sell_price", "line_ids.cost")
    def _compute_totals(self):
        for rec in self:
            rec.items_count = len(rec.line_ids)
            rec.total_sell_price = sum(rec.line_ids.mapped("sell_price"))
            rec.total_cost = sum(rec.line_ids.mapped("cost"))

    @api.model
    def get_transfer_dashboard_payload(self):
        today = fields.Date.context_today(self)
        today_start = fields.Datetime.to_string(datetime.combine(today, time.min))

        Transfer = self.env["ab_transfer_header"].sudo()
        Request = self.env["ab_transfer_request"].sudo()
        Receive = self.env["ab_transfer_receive_header"].sudo()
        RequestReport = self.env["ab_transfer_request_report"].sudo()

        pending_transfers = Transfer.search_count([("selection", "=", "pending")])
        draft_transfers = Transfer.search_count([("selection", "=", "prepending")])
        submitted_today = Transfer.search_count([
            ("is_submitted", "=", True),
            ("sent_at", ">=", today_start),
        ])
        pending_receives = Receive.search_count([("state", "=", "pending")])
        pending_requests = Request.search_count([
            ("state", "=", "confirmed"),
            ("execution_state", "=", "pending"),
        ])

        report_rows = RequestReport._read_group(
            [],
            groupby=["execution_status"],
            aggregates=["__count"],
        )
        report_counts = {
            execution_status: count
            for execution_status, count in report_rows
            if execution_status
        }

        return {
            "updated_at": fields.Datetime.to_string(fields.Datetime.now()),
            "quick_actions": [
                {
                    "key": "fast_transfer",
                    "title": _("Fast Transfer"),
                    "icon": "fa-bolt",
                    "tone": "primary",
                    "action": "ab_transfer.ab_transfer_pos_action",
                },
                {
                    "key": "smart_transfer",
                    "title": _("Smart Transfer"),
                    "icon": "fa-random",
                    "tone": "teal",
                    "action": "ab_transfer.ab_transfer_header_action",
                },
                {
                    "key": "transfer_request",
                    "title": _("Transfer Request"),
                    "icon": "fa-list-alt",
                    "tone": "amber",
                    "action": "ab_transfer.ab_transfer_request_action",
                },
                {
                    "key": "receive_transfer",
                    "title": _("Receive Transfer"),
                    "icon": "fa-download",
                    "tone": "blue",
                    "action": "ab_transfer.ab_transfer_receive_header_action",
                },
                {
                    "key": "request_report",
                    "title": _("Request Report"),
                    "icon": "fa-bar-chart",
                    "tone": "slate",
                    "action": "ab_transfer.ab_transfer_request_report_action",
                },
            ],
            "metrics": [
                {
                    "key": "pending_transfers",
                    "label": _("Pending Transfers"),
                    "value": pending_transfers,
                    "icon": "fa-clock-o",
                    "tone": "warning",
                    "action": {
                        "type": "ir.actions.act_window",
                        "name": _("Pending Transfers"),
                        "res_model": "ab_transfer_header",
                        "view_mode": "list,form",
                        "views": [[False, "list"], [False, "form"]],
                        "domain": [["selection", "=", "pending"]],
                        "context": {"search_default_filter_pending": 1},
                    },
                },
                {
                    "key": "pending_receives",
                    "label": _("Pending Receives"),
                    "value": pending_receives,
                    "icon": "fa-inbox",
                    "tone": "danger",
                    "action": "ab_transfer.ab_transfer_receive_header_action",
                },
                {
                    "key": "pending_requests",
                    "label": _("Pending Requests"),
                    "value": pending_requests,
                    "icon": "fa-tasks",
                    "tone": "primary",
                    "action": {
                        "type": "ir.actions.act_window",
                        "name": _("Pending Transfer Requests"),
                        "res_model": "ab_transfer_request",
                        "view_mode": "list,form",
                        "views": [[False, "list"], [False, "form"]],
                        "domain": [
                            ["state", "=", "confirmed"],
                            ["execution_state", "=", "pending"],
                        ],
                        "context": {
                            "search_default_filter_confirmed": 1,
                            "search_default_filter_execution_pending": 1,
                        },
                    },
                },
                {
                    "key": "submitted_today",
                    "label": _("Submitted Today"),
                    "value": submitted_today,
                    "icon": "fa-check-circle",
                    "tone": "success",
                    "action": {
                        "type": "ir.actions.act_window",
                        "name": _("Submitted Today"),
                        "res_model": "ab_transfer_header",
                        "view_mode": "list,form",
                        "views": [[False, "list"], [False, "form"]],
                        "domain": [
                            ["is_submitted", "=", True],
                            ["sent_at", ">=", today_start],
                        ],
                        "context": {},
                    },
                },
            ],
            "request_execution": [
                {
                    "key": "pending",
                    "label": _("Pending"),
                    "value": report_counts.get("pending", 0),
                    "tone": "danger",
                },
                {
                    "key": "partially_executed",
                    "label": _("Partial"),
                    "value": report_counts.get("partially_executed", 0),
                    "tone": "warning",
                },
                {
                    "key": "fully_executed",
                    "label": _("Done"),
                    "value": report_counts.get("fully_executed", 0),
                    "tone": "success",
                },
            ],
            "draft_transfers": draft_transfers,
        }

    @api.constrains("from_store_id", "to_store_id")
    def _check_store_difference(self):
        for rec in self:
            if rec.from_store_id and rec.to_store_id and rec.from_store_id == rec.to_store_id:
                raise ValidationError(_("Source store and destination store cannot be the same."))

    @api.constrains("from_store_id")
    def _check_source_store_allowed(self):
        store_ids = self._get_allowed_source_store_ids()
        if not store_ids:
            return
        for rec in self:
            if rec.from_store_id and rec.from_store_id.id not in store_ids:
                raise ValidationError(
                    _("Source store %s is not allowed for sales POS.") % rec.from_store_id.display_name)

    @api.constrains("line_ids")
    def _check_lines_exist_when_saved(self):
        for rec in self:
            if rec.selection in ("pending", "saved") and not rec.line_ids:
                raise ValidationError(_("You cannot continue without lines."))

    def _check_not_is_submitted(self):
        locked = self.filtered("is_submitted")
        if locked:
            raise UserError(_("Submitted transfers cannot be edited."))

    def write(self, vals):
        if vals and any(rec.is_submitted for rec in self):
            allowed_after_submit = {
                "error_message",
            }
            if set(vals) - allowed_after_submit:
                self._check_not_is_submitted()
        return super().write(vals)

    def unlink(self):
        self._check_not_is_submitted()
        return super().unlink()

    # =========================
    # Public Button Action
    # =========================
    def action_submit(self):
        self.ensure_one()

        if self.is_submitted:
            raise ValidationError(_("تم إرسال هذا التحويل إلى إي بلس مسبقًا."))

        line_model = self.env["ab_transfer_line"]
        lines = line_model.search([("header_id", "=", self.id)])

        if not lines:
            raise ValidationError(_("لا يمكن الإرسال بدون أصناف."))

        self._validate_odoo_data(lines)

        try:
            with self._get_sql_connection() as conn:
                cursor = conn.cursor()
                try:
                    # 1) Validations from SQL Server
                    sql_ctx = self._validate_sql_prerequisites(cursor, lines)

                    # 2) Write header
                    sql_flag = 'S'  # self._map_sql_flag(self.selection)

                    from_store_sql_id = self._get_ref_id(self.from_store_id, "المخزن المصدر")
                    to_store_sql_id = self._get_ref_id(self.to_store_id, "المخزن الهدف")
                    insert_user_sql_id = self._get_ref_id(self.user_id, "المستخدم")

                    total_sell_price = self.total_sell_price or 0.0
                    items_count = self.items_count or len(lines)
                    notes = self.notes or ""
                    store_trans_h_notes = self._build_submit_store_trans_h_notes()
                    delivery_emp_sql_id = self._get_ref_id(
                        self.employee_delivery_id, "موظف التسليم", allow_empty=True
                    )

                    stnh_pend_affect_stk = sql_ctx["stnh_pend_affect_stk"]

                    cursor.execute(
                        """
                        SET NOCOUNT ON;
                        DECLARE @new_store_trans_h TABLE (stnh_id int);

                        INSERT INTO Store_Trans_h (stnh_f_Sto_id,
                                                   stnh_t_Sto_id,
                                                   stnh_tot_sell_value,
                                                   stnh_tot_cost_value,
                                                   stnh_no_items,
                                                   stnh_notes,
                                                   stnh_flag,
                                                   sec_insert_uid,
                                                   stnh_avg_cost,
                                                   stnh_toh_id,
                                                   sec_update_uid,
                                                   sec_update_date,
                                                   stnh_pend_affect_stk,
                                                   delivery_emp)
                        OUTPUT INSERTED.stnh_id INTO @new_store_trans_h
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, GETDATE(), ?, ?)

                        SELECT stnh_id FROM @new_store_trans_h
                        """,
                        (
                            from_store_sql_id,
                            to_store_sql_id,
                            total_sell_price,
                            0,
                            items_count,
                            store_trans_h_notes,
                            sql_flag,
                            insert_user_sql_id,
                            0,
                            0,
                            insert_user_sql_id,
                            stnh_pend_affect_stk,
                            delivery_emp_sql_id,
                        ),
                    )
                    sql_header_row = cursor.fetchone()
                    sql_header_id = int(sql_header_row[0]) if sql_header_row and sql_header_row[0] else 0
                    if not sql_header_id:
                        raise ValidationError(_("SQL Server did not return Store_Trans_h.stnh_id."))

                    total_cost_accum = 0.0

                    # 3) Write lines + stock updates + replication
                    for line in lines:
                        line_ctx = self._prepare_line_context(cursor, line)

                        total_cost_accum += line_ctx["cost"]

                        cursor.execute(
                            """
                            INSERT INTO Store_Trans (stnh_id,
                                                     st_from_store,
                                                     st_to_store,
                                                     st_itm_id,
                                                     st_c_id,
                                                     st_itm_quantity,
                                                     st_itm_expiry,
                                                     sec_insert_uid,
                                                     st_itm_sell,
                                                     st_itm_cost,
                                                     st_itm_received_qty,
                                                     st_itm_unit,
                                                     st_from_stk,
                                                     st_itm_pharm_price,
                                                     st_itm_tax,
                                                     st_requested_qty,
                                                     st_f_itm_purchase_unit,
                                                     st_f_itm_unit1_unit2,
                                                     st_f_itm_unit1_unit3)
                            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                            """,
                            (
                                sql_header_id,
                                line_ctx["from_store_sql_id"],
                                line_ctx["to_store_sql_id"],
                                line_ctx["product_sql_id"],
                                line_ctx["class_id"],
                                line_ctx["qty"],
                                line_ctx["expiry_date"],
                                line_ctx["insert_user_sql_id"],
                                line_ctx["sell_price"],
                                line_ctx["cost"],
                                0,
                                line_ctx["uom_sql_id"],
                                line_ctx["current_stock"],
                                line_ctx["purchase_price"],
                                line_ctx["tax_value"],
                                line.requested_qty or 0,
                                line_ctx["itm_purchase_unit"],
                                line_ctx["itm_unit1_unit2"],
                                line_ctx["itm_unit1_unit3"],
                            ),
                        )

                        cursor.execute(
                            """
                            UPDATE Item_Class_Store
                            SET itm_qty         = ISNULL(itm_qty, 0) - ?,
                                sec_update_uid  = ?,
                                sec_update_date = GETDATE()
                            WHERE c_id = ?
                              AND sto_id = ?
                              AND itm_id = ?
                            """,
                            (
                                line_ctx["qty"],
                                str(line_ctx["insert_user_sql_id"]),
                                line_ctx["class_id"],
                                line_ctx["from_store_sql_id"],
                                line_ctx["product_sql_id"],
                            ),
                        )
                        if sql_ctx["has_replication"]:
                            cursor.execute(
                                """
                                INSERT INTO Replication_Trans (trans_typ_1,
                                                               trans_typ_2,
                                                               store_id,
                                                               store_id2,
                                                               itm_id,
                                                               class_id,
                                                               class_id_ext1,
                                                               class_id_ext2,
                                                               itm_qty,
                                                               itm_expire,
                                                               general_id,
                                                               general_name,
                                                               trans_qry,
                                                               sec_insert_uid,
                                                               form_nm,
                                                               ePlusVersion)
                                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                                """,
                                (
                                    10,
                                    1,
                                    line_ctx["from_store_sql_id"],
                                    line_ctx["to_store_sql_id"],
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    None,
                                    sql_header_id,
                                    "Transfere EZN Sarf",
                                    "",
                                    line_ctx["insert_user_sql_id"],
                                    "new_store_transfer_ar",
                                    "e-Plus",
                                ),
                            )

                    cursor.execute(
                        """
                        UPDATE st
                        SET st.st_itm_expiry = ics.itm_expiry_date FROM Store_Trans st
                        INNER JOIN Item_Class_Store ics
                        ON ics.sto_id = st.st_from_store
                            AND ics.itm_id = st.st_itm_id
                            AND ics.c_id = st.st_c_id
                        WHERE st.stnh_id = ? AND st.st_from_store = ?
                        """,
                        (sql_header_id, from_store_sql_id),
                    )

                    cursor.execute(
                        """
                        UPDATE st
                        SET st.st_batch_no = k.itm_batch_no FROM Store_Trans st
                        INNER JOIN item_class k
                        ON k.itm_id = st.st_itm_id
                            AND k.c_id = st.st_c_id
                        WHERE st.stnh_id = ? AND st.st_from_store = ?
                        """,
                        (sql_header_id, from_store_sql_id),
                    )

                    cursor.execute(
                        """
                        UPDATE Store_Trans_h
                        SET stnh_tot_cost_value = ?
                        WHERE stnh_id = ?
                          AND stnh_f_Sto_id = ?
                        """,
                        (total_cost_accum, sql_header_id, from_store_sql_id),
                    )

                    if sql_ctx["to_store_acc_id"] > 0:
                        cursor.execute(
                            """
                            INSERT INTO F_Auto_Doc_h (fah_type,
                                                      fah_sto_id,
                                                      fah_form_name,
                                                      fah_form_id,
                                                      fah_form_notes,
                                                      fah_total_value,
                                                      fah_description,
                                                      fah_ePlus_version,
                                                      fah_starting_doc,
                                                      sec_insert_uid,
                                                      fah_form_text,
                                                      fah_computer_name)
                            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                            """,
                            (
                                "StockTransOut",
                                from_store_sql_id,
                                "new_store_transfer_ar",
                                sql_header_id,
                                notes,
                                0,
                                f"إذن صرف {sql_header_id}",
                                "13.0.92",
                                0,
                                insert_user_sql_id,
                                "تحويلات مخازن",
                                self._get_computer_name(),
                            ),
                        )

                        cursor.execute("SELECT SCOPE_IDENTITY()")
                        fah_id_row = cursor.fetchone()
                        fah_id = int(fah_id_row[0]) if fah_id_row and fah_id_row[0] else 0

                        if fah_id:
                            cursor.execute(
                                """
                                INSERT INTO F_Auto_Doc_d (fad_fah_id,
                                                          fad_group_id,
                                                          fad_value,
                                                          fad_D_Account_id,
                                                          fad_D_Account_name,
                                                          fad_D_object,
                                                          fad_D_object_id,
                                                          fad_C_Account_id,
                                                          fad_C_Account_name,
                                                          fad_C_object,
                                                          fad_C_object_id,
                                                          sec_insert_uid)
                                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                                """,
                                (
                                    fah_id,
                                    1,
                                    total_cost_accum,
                                    sql_ctx["to_store_acc_id"],
                                    str(sql_ctx["to_store_acc_id"]),
                                    "Stor",
                                    to_store_sql_id,
                                    35,
                                    "Stock",
                                    "Stor",
                                    from_store_sql_id,
                                    insert_user_sql_id,
                                ),
                            )

                            cursor.execute(
                                """
                                UPDATE F_Auto_Doc_h
                                SET fah_total_value = ?
                                WHERE fah_id = ?
                                """,
                                (total_cost_accum, fah_id),
                            )

                    conn.commit()

                    self.write({
                        "selection": "saved",
                        "is_submitted": True,
                        "sent_at": fields.Datetime.now(),
                        "error_message": False,
                    })

                    return True
                except Exception:
                    conn.rollback()
                    raise
                finally:
                    cursor.close()

        except Exception as exc:
            error_message = str(exc)
            _logger.exception("EPlus transfer failed for header ID %s", self.id)

            self.write({
                "error_message": error_message,
            })

            raise ValidationError(_("فشل إرسال التحويل إلى إي بلس:\n%s") % error_message)

        # =========================
        # Odoo Validations
        # =========================

    def _build_submit_store_trans_h_notes(self):
        self.ensure_one()
        transfer_reference = "Odoo Transfer: %s" % self.display_name
        notes = self.notes or ""
        if notes:
            if notes.strip() in {"1", "2", "3", "4"}:
                return "%s %s" % (notes, transfer_reference)
            return "%s\n%s" % (notes, transfer_reference)
        return transfer_reference

    def _validate_odoo_data(self, lines):
        self.ensure_one()

        required_header_fields = [
            ("from_store_id", "المخزن المصدر"),
            ("to_store_id", "المخزن الهدف"),
            ("user_id", "المستخدم"),
        ]

        for field_name, label in required_header_fields:
            if not getattr(self, field_name):
                raise ValidationError(_("الحقل مطلوب: %s") % label)

        for line in lines:
            required_line_fields = [
                ("from_store_id", "المخزن المصدر"),
                ("to_store_id", "المخزن الهدف"),
                ("product_id", "الصنف"),
                ("class_id", "التصنيف"),
                ("qty", "الكمية"),
                ("uom_id", "الوحدة"),
                ("user_id", "المستخدم"),
            ]

            for field_name, label in required_line_fields:
                value = getattr(line, field_name)
                if value in (False, None, "", 0):
                    raise ValidationError(
                        _("يوجد نقص في بيانات السطر %s. الحقل المطلوب: %s") % (line.display_name, label)
                    )

            if line.qty <= 0:
                raise ValidationError(_("الكمية يجب أن تكون أكبر من صفر في السطر %s.") % line.display_name)

    # =========================
    # SQL Validations
    # =========================
    def _validate_sql_prerequisites(self, cursor, lines):
        self.ensure_one()

        to_store_sql_id = self._get_ref_id(self.to_store_id, "المخزن الهدف")

        # تفعيل المخزن الهدف
        cursor.execute(
            "SELECT ISNULL(activated, 1) FROM store WHERE sto_id = ?",
            (to_store_sql_id,),
        )
        row = cursor.fetchone()
        if not row:
            raise ValidationError(_("المخزن الهدف غير موجود في SQL Server."))
        if not int(row[0]):
            raise ValidationError(_("المخزن الهدف غير مفعل في SQL Server."))

        # Replication flag
        cursor.execute("SELECT ISNULL(has_replication, 0) FROM Sys_setting")
        row = cursor.fetchone()
        has_replication = bool(row and int(row[0] or 0) == 1)

        # Pending affect stock
        cursor.execute("SELECT ISNULL(ss_pend_affect_stk, 0) FROM s_sto")
        row = cursor.fetchone()
        stnh_pend_affect_stk = int(row[0] or 0) if row else 0

        # Target store accounting account
        cursor.execute(
            "SELECT ISNULL(sto_acc_id, 0) FROM store WITH(NOLOCK) WHERE sto_id = ?",
            (to_store_sql_id,),
        )
        row = cursor.fetchone()
        to_store_acc_id = int(row[0] or 0) if row else 0

        # Validate every line against product and stock
        for line in lines:
            self._validate_sql_line(cursor, line)

        return {
            "has_replication": has_replication,
            "stnh_pend_affect_stk": stnh_pend_affect_stk,
            "to_store_acc_id": to_store_acc_id,
        }

    def _validate_sql_line(self, cursor, line):
        from_store_sql_id = self._get_ref_id(line.from_store_id, "المخزن المصدر")
        product_sql_id = self._get_ref_id(line.product_id, "الصنف")
        class_id = self._normalize_scalar(line.class_id, "التصنيف")
        qty_in_stock_uom = self._line_qty_in_stock_uom(line)

        # الصنف موجود في item_catalog
        cursor.execute(
            "SELECT COUNT(1) FROM item_catalog WHERE itm_id = ?",
            (product_sql_id,),
        )
        row = cursor.fetchone()
        if not row or int(row[0] or 0) == 0:
            raise ValidationError(
                _("الصنف %s غير موجود في item_catalog على SQL Server.") % line.product_id.display_name
            )

        # تاريخ الصلاحية
        if not line.expiry_date:
            raise ValidationError(
                _("تاريخ الصلاحية مطلوب للصنف %s.") % line.product_id.display_name
            )

        # رصيد كافٍ
        cursor.execute(
            """
            SELECT ISNULL(ROUND(itm_qty, 1), 0) AS QTY
            FROM Item_Class_Store
            WHERE c_id = ?
              AND itm_id = ?
              AND sto_id = ?
            """,
            (class_id, product_sql_id, from_store_sql_id),
        )
        row = cursor.fetchone()
        stock_qty = float(row[0] or 0.0) if row else 0.0

        if stock_qty < qty_in_stock_uom:
            raise ValidationError(
                _("الرصيد غير كافٍ للصنف %s في المخزن المصدر. المتاح: %s / المطلوب: %s")
                % (line.product_id.display_name, stock_qty, qty_in_stock_uom)
            )

    # =========================
    # Prepare Each Line
    # =========================
    def _prepare_line_context(self, cursor, line):
        from_store_sql_id = self._get_ref_id(line.from_store_id, "المخزن المصدر")
        to_store_sql_id = self._get_ref_id(line.to_store_id, "المخزن الهدف")
        product_sql_id = self._get_ref_id(line.product_id, "الصنف")
        insert_user_sql_id = self._get_ref_id(line.user_id, "المستخدم")
        class_id = self._normalize_scalar(line.class_id, "التصنيف")

        qty = self._line_qty_in_stock_uom(line)

        expiry_date = line.expiry_date
        if isinstance(expiry_date, str):
            expiry_value = expiry_date
        else:
            expiry_value = fields.Date.to_string(expiry_date) if expiry_date else None

        # item_catalog data
        cursor.execute(
            """
            SELECT ISNULL(itm_purchase_unit, 1),
                   ISNULL(itm_unit1_unit2, 1),
                   ISNULL(itm_unit1_unit3, 1)
            FROM item_catalog
            WHERE itm_id = ?
            """,
            (product_sql_id,),
        )
        row = cursor.fetchone()
        if not row:
            raise ValidationError(
                _("تعذر قراءة بيانات الوحدة للصنف %s من item_catalog.") % line.product_id.display_name)

        itm_purchase_unit = int(row[0] or 1)
        itm_unit1_unit2 = int(row[1] or 1)
        itm_unit1_unit3 = int(row[2] or 1)
        uom_sql_id = itm_purchase_unit

        unit_factor = 1.0
        if itm_purchase_unit == 1:
            unit_factor = 1.0
        elif itm_purchase_unit == 2:
            unit_factor = float(itm_unit1_unit2 or 1)
        else:
            unit_factor = float(itm_unit1_unit3 or 1)

        # stock row pricing
        cursor.execute(
            """
            SELECT ISNULL(pharm_price, 0),
                   ISNULL(sell_price, 0),
                   ISNULL(sell_tax, 0),
                   ISNULL(itm_qty, 0),
                   itm_expiry_date
            FROM Item_Class_Store
            WHERE c_id = ?
              AND itm_id = ?
              AND sto_id = ?
            """,
            (class_id, product_sql_id, from_store_sql_id),
        )
        row = cursor.fetchone()
        if not row:
            raise ValidationError(
                _("لا توجد بيانات مخزون للصنف %s في Item_Class_Store.")
                % line.product_id.display_name
            )

        pharm_price = float(row[0] or 0.0)
        sell_price_base = float(row[1] or 0.0)
        sell_tax_base = float(row[2] or 0.0)
        current_stock = float(row[3] or 0.0)

        purchase_price = pharm_price * unit_factor
        sell_price = sell_price_base * unit_factor
        tax_value = sell_tax_base * unit_factor

        # cost:
        # طبقًا للسكربت القديم: st_itm_cost كان مساويًا لـ pharm_price * unit_factor
        cost = purchase_price

        return {
            "from_store_sql_id": from_store_sql_id,
            "to_store_sql_id": to_store_sql_id,
            "product_sql_id": product_sql_id,
            "class_id": class_id,
            "qty": qty,
            "expiry_date": expiry_value,
            "insert_user_sql_id": insert_user_sql_id,
            "sell_price": sell_price,
            "cost": cost,
            "uom_sql_id": uom_sql_id,
            "current_stock": current_stock,
            "purchase_price": purchase_price,
            "tax_value": tax_value,
            "itm_purchase_unit": itm_purchase_unit,
            "itm_unit1_unit2": itm_unit1_unit2,
            "itm_unit1_unit3": itm_unit1_unit3,
        }

    # =========================
    # Helpers
    # =========================
    def _line_qty_in_stock_uom(self, line):
        qty = float(line.qty or 0.0)
        uom_factor = line.uom_id.factor if line.uom_id and line.uom_id.factor else 1.0
        return qty * float(uom_factor or 1.0)

    def _get_sql_connection(self):
        store = self.from_store_id or self._get_default_source_store()
        server = store.ip1 or store.ip2 if store else None
        if not server:
            raise ValidationError(_("Source store MSSQL server IP is missing."))
        return self.connect_eplus(
            server=server,
            param_str="?",
            autocommit=False,
            propagate_error=True,
        )

    def _get_ref_id(self, record, label, allow_empty=False):
        if not record:
            if allow_empty:
                return None
            raise ValidationError(_("الحقل مطلوب: %s") % label)

        ref_fields_by_model = {
            "ab_store": "eplus_serial",
            "ab_product": "eplus_serial",
            "ab_costcenter": "eplus_serial",
        }
        field_name = ref_fields_by_model.get(record._name)
        if not field_name:
            raise ValidationError(
                _("لا يوجد حقل معرف خارجي مضبوط للموديل %(model)s في الحقل: %(label)s")
                % {"model": record._name, "label": label}
            )
        if field_name not in record._fields:
            raise ValidationError(
                _("الحقل %(field)s غير موجود على الموديل %(model)s.")
                % {"field": field_name, "model": record._name}
            )

        value = record[field_name]
        if value in (False, None, "", 0):
            if allow_empty:
                return None
            raise ValidationError(_("تعذر استخراج المعرف الخارجي للحقل: %s") % label)

        return int(value)

    def _normalize_scalar(self, value, label):
        if value in (False, None, "", 0):
            raise ValidationError(_("الحقل مطلوب: %s") % label)

        if hasattr(value, "_name"):
            return self._get_ref_id(value, label)

        return int(value)

    def _map_sql_flag(self, selection_value):
        """
        عدّل هذا الـ mapping حسب القيم الفعلية المطلوبة في SQL Server.
        السكربت القديم كان يستخدم 'S'.
        """
        mapping = {
            "prepending": "P",
            "pending": "N",
            "saved": "S",
        }

        sql_flag = mapping.get(selection_value)
        if not sql_flag:
            raise ValidationError(
                _("قيمة selection غير معرفة في mapping الخاص بـ SQL: %s") % selection_value
            )
        return sql_flag

    def _get_computer_name(self):
        ICP = self.env["ir.config_parameter"].sudo()
        return ICP.get_param("ab_eplus.computer_name") or "ODOO"
