{
    "name": "Ab Sales HR",
    "version": "19.0.1.0.0",
    "license": "LGPL-3",
    "category": "AbdinSupplyChain",
    "summary": "Branch service-user POS with employee PIN, roles, shifts, and audit logs.",
    "depends": [
        "ab_odoo_sync",
        "ab_widgets",
        "ab_sales",
        "ab_employee_access",
    ],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "views/menus.xml",
        "views/ab_employee_access_sales_shift_views.xml",
        "views/ab_employee_access_sales_pos_session_views.xml",
        "views/ab_employee_access_sales_operation_log_views.xml",
        "views/ab_sales_header_views.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
