{
    'name': 'Abdin Inventory',
    'version': '19.0.1.0.0',
    'license': 'LGPL-3',
    'category': 'AbdinSupplyChain',
    'author': 'Abdin Pharmacies',
    'developer': 'emadco88',
    'application': True,
    'depends': [
        'base',
        'ab_product',
        'ab_product_source',
        'ab_store',
    ],
    'data': [
        'security/security_groups.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'views/ab_inventory_movements.xml',
        'report/ab_inventory_period_report.xml',
        'report/ab_inventory_balance_report.xml',
        'views/res_users_inventory.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'auto_install': False,
}
