from odoo import api, fields, models, _
from odoo.exceptions import AccessError, UserError


class DeployScriptUpdate(models.TransientModel):
    _name = 'ab_deploy_script_update'
    _description = 'Update Deployment Commands'

    request_id = fields.Many2one('ab_deploy_request', required=True, readonly=True)
    target_ids = fields.Many2many('ab_deploy_target', string='Servers to Update', readonly=True)
    reason = fields.Text(string='Update Reason')
    proposals = fields.Json(readonly=True)
    preview = fields.Text(string='Script Changes', readonly=True)
    confirmed = fields.Boolean(readonly=True)

    @api.model_create_multi
    def create(self, vals_list):
        raise AccessError(_('Open Update Commands from the deployment request.'))

    def write(self, vals):
        if set(vals) != {'reason'}:
            raise AccessError(_('Script previews are generated by the deployment workflow.'))
        self.check_access('write')
        for wizard in self:
            wizard.request_id._check_revision_admin()
            if wizard.confirmed:
                raise UserError(_('This command update has already been confirmed.'))
        return super().write(vals)

    @api.model
    def _open(self, request, proposals):
        request._check_revision_admin()
        before_label, after_label = _('Previously Approved Script'), _('Proposed Script')
        names = {target.id: target.server_id.display_name for target in request.target_ids}
        preview = '\n\n'.join('%s\n%s\n%s\n%s\n%s\n%s' % (
            names[row['target_id']], row['script_diff'], before_label, row['before_script'],
            after_label, row['after_script']) for row in proposals)
        return super().create({'request_id': request.id,
            'target_ids': [fields.Command.set([row['target_id'] for row in proposals])],
            'reason': False, 'proposals': proposals, 'preview': preview, 'confirmed': False})

    def action_confirm(self):
        self.ensure_one()
        self.check_access('write')
        self.request_id._check_revision_admin()
        self.lock_for_update()
        self.invalidate_recordset()
        if self.confirmed:
            raise UserError(_('This command update has already been confirmed.'))
        self.env['ab_deploy_script_revision']._confirm(self.request_id, self.reason, self.proposals)
        super().write({'confirmed': True})
        return {'type': 'ir.actions.client', 'tag': 'reload'}
